// Food Categories List
const List<String> foodCategories = [
  'Fruits',
  'Vegetables',
  'Dairy',
  'Meat',
  'Poultry',
  'Seafood',
  'Grains',
  'Bread',
  'Pasta',
  'Snacks',
  'Beverages',
  'Condiments',
  'Sauces',
  'Spices',
  'Herbs',
  'Baking Supplies',
  'Canned Goods',
  'Frozen Foods',
  'Ready-to-eat Meals',
  'Breakfast Foods',
  'Desserts',
  'Nuts and Seeds',
  'Oils and Vinegars',
  'Processed Foods',
  'Baby Food',
  'Pet Food',
  'Health Foods',
  'Organic Products',
  'Gluten-free Products',
  'International Foods',
  'Others'
];
