// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkoJQL_N-glGVIZ56fg0p29a9vbcBsBoQ',
    appId: '1:128923439893:web:b84481b0fb37a34de68f1c',
    messagingSenderId: '128923439893',
    projectId: 'grocery-ad65a',
    authDomain: 'grocery-ad65a.firebaseapp.com',
    storageBucket: 'grocery-ad65a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FbMSHIHwb4yYJcRUSqibMv95Xjs7Mt0',
    appId: '1:128923439893:android:89c70d570b39f044e68f1c',
    messagingSenderId: '128923439893',
    projectId: 'grocery-ad65a',
    storageBucket: 'grocery-ad65a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPffayGGi2VsAfMGhLZh9E9RUo2Ki5pu4',
    appId: '1:128923439893:ios:3d2b45023b3526c0e68f1c',
    messagingSenderId: '128923439893',
    projectId: 'grocery-ad65a',
    storageBucket: 'grocery-ad65a.firebasestorage.app',
    androidClientId: '128923439893-magagp6qneomnb4lg3gs4jtjrc1hjapq.apps.googleusercontent.com',
    iosClientId: '128923439893-1g6afd3tf2hfqhib9jtlqu4qnb0nr02e.apps.googleusercontent.com',
    iosBundleId: 'com.mam.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPffayGGi2VsAfMGhLZh9E9RUo2Ki5pu4',
    appId: '1:128923439893:ios:3d2b45023b3526c0e68f1c',
    messagingSenderId: '128923439893',
    projectId: 'grocery-ad65a',
    storageBucket: 'grocery-ad65a.firebasestorage.app',
    androidClientId: '128923439893-magagp6qneomnb4lg3gs4jtjrc1hjapq.apps.googleusercontent.com',
    iosClientId: '128923439893-1g6afd3tf2hfqhib9jtlqu4qnb0nr02e.apps.googleusercontent.com',
    iosBundleId: 'com.mam.grocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkoJQL_N-glGVIZ56fg0p29a9vbcBsBoQ',
    appId: '1:128923439893:web:2a8dd27d726f6f3ce68f1c',
    messagingSenderId: '128923439893',
    projectId: 'grocery-ad65a',
    authDomain: 'grocery-ad65a.firebaseapp.com',
    storageBucket: 'grocery-ad65a.firebasestorage.app',
  );
}
